# Streamlit 設定ファイル（サンプル）
# 実際の設定では、secrets.toml として保存してください

[auth]
client_id = "your-google-oauth-client-id.apps.googleusercontent.com"
client_secret = "your-google-oauth-client-secret"
redirect_uri = "http://localhost:8701/"
cookie_secret = "your-random-cookie-secret-32-chars-long"

[database]
supabase_url = "https://your-project.supabase.co"
supabase_key = "your-supabase-anon-key"

[ai]
gemini_api_key = "your-gemini-api-key"

[google_drive]
type = "service_account"
project_id = "your-gcp-project-id"
private_key_id = "your-private-key-id"
private_key = "-----BEGIN PRIVATE KEY-----\nyour-private-key\n-----END PRIVATE KEY-----\n"
client_email = "your-service-account@your-project.iam.gserviceaccount.com"
client_id = "your-client-id"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/your-service-account%40your-project.iam.gserviceaccount.com"
# オプション: 特定フォルダにアップロードしたい場合
# default_folder_id = "your-google-drive-folder-id"

[google_sheets]
# Google Sheetsも同じサービスアカウントを使用
# 追加設定は不要（google_driveセクションの設定を流用）

# セキュリティ注意事項:
# - このファイルは絶対にGitにコミットしないでください
# - .gitignoreに*.tomlを追加してください
# - 本番環境では環境変数やSecret Managerを使用してください 